# Generated by Django 4.2.27 on 2025-12-12 06:01

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamepost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamepost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='gamepost',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamepost',
            name='gameimage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gamepost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
